### PR TITLE
Handle checking for empty request body when that is an object

### LINKED ISSUE #65: ContentTypeFilterListener fails to detect empty request body when used with the Request object from zend/psr7bridge
This is due to the fact, that `$requestBody = $request->getContent();` returns a StreamInterface (from zend/diactoros), I am referring to this line `ContentTypeFilterListener.php:71`. 

Calling `empty($requestBody)` will return false, while `empty($requestBody->getContents())` can return true if the actual request didn't have any payload (like a GET request).

I am not sure if the fix needs to happen here or maybe in zend/psr7bridge or maybe in zend/diactoros. 

The reason I am raising this here still, is that it seems there's an incorrect assumption being made: it is incorrectly assumed that whatever `$request->getContent();` returns can be used with `empty()` correctly, but that is not exactly true.

I came accross this issue by having wrapped a ZF2/Apigility app in a middleware and used zend/psr7bridge to translate between Zend and PSR7 request/response formats. Suddenly I am getting "415 - Unsupported Media Type" even for GET requests, because the translated request objects always have a StreamInterface object as their bodies, even when that stream is actually empty.

### PR DESCRIPTION
**Pull request by boteeka**
Fixes #65

### CODE REVIEW

File: src/ContentTypeFilterListener.php [hunk 1]
```diff
@@ -68,6 +68,12 @@ public function onRoute(MvcEvent $e)
         }
 
         $requestBody = $request->getContent();
+
+        // If the $requestBody happens to be an object, unwrap its actual contents
+        if (is_object($requestBody) && method_exists($requestBody, 'getContents')) {
+            $requestBody = $requestBody->getContents();
```
Comment (weierophinney) [inline src/ContentTypeFilterListener.php]: I'd argue instead that we cast the body to a string. This ensures the `empty()` check works, and will work flawlessly with PSR-7 bodies as well (as casting to a string internally calls `getContents()`).

I'll make that change on merge, and add a unit test.
